# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cAddr',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='cEmail',
            field=models.EmailField(blank=True, default='', max_length=100),
        ),
    ]
