# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20171130_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='sdgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdg_Name', models.CharField(max_length=20)),
                ('sdg_Num', models.CharField(max_length=20)),
                ('sdg_Goal', models.CharField(max_length=20)),
            ],
        ),
    ]
