# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_sdgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdgs',
            name='sdg_img_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
