# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_sdgs_sdg_img_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='gri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=200)),
                ('ds_type', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('aspect', models.CharField(max_length=200)),
                ('indicator', models.CharField(max_length=200)),
                ('guidance', models.CharField(max_length=200)),
                ('disclosure', models.CharField(max_length=200)),
                ('assurance_third', models.CharField(max_length=200)),
                ('assurance_account', models.CharField(max_length=200)),
            ],
        ),
    ]
